version: '3.4'
services:
  ndexbase-rstudio:
    image: fdrennan/drenrbase
    restart: "always"
    user: 'root'
    volumes:
      - ./main.sh:/home/main.sh:ro
    ports:
      - "80:8787"
    command: ["sh", "/home/main.sh"]
